on:
  push:
  pull_request:
name: CI
jobs:
  flatpak:
    name: Flatpak Builder
    runs-on: ubuntu-20.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:elementary-juno
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
        with:
          bundle: iridium.flatpak
          manifest-path: com.github.avojak.iridium.yml
          repository-name: appcenter
          repository-url: https://flatpak.elementary.io/repo.flatpakrepo
          cache-key: "flatpak-builder-${{ github.sha }}"
